INSERT INTO torneo(nome,anno,descrizione,id)VALUES('Champions League',2024,'Competizione europea tra le migliori squadre dei campionati nazionali.',nextval('torneo_seq'));
INSERT INTO torneo(nome,anno,descrizione,id)VALUES('Europa League',2024,'Competizione europea per squadre non qualificate alla Champions League.',nextval('torneo_seq'));
INSERT INTO torneo(nome,anno,descrizione,id)VALUES('Serie A',2025,'Campionato italiano di calcio di massima serie.',nextval('torneo_seq'));
INSERT INTO torneo(nome,anno,descrizione,id)VALUES('Coppa Italia',2025,'Competizione nazionale a eliminazione diretta tra squadre italiane.',nextval('torneo_seq'));
INSERT INTO torneo(nome,anno,descrizione,id)VALUES('Mondiale per Club',2025,'Torneo internazionale tra club campioni dei vari continenti.',nextval('torneo_seq'));
INSERT INTO squadre(id, nome, anno_fondazione, citta) VALUES (nextval('squadre_seq'),'Roma',1927,'Roma');
INSERT INTO squadre(id, nome, anno_fondazione, citta) VALUES (nextval('squadre_seq'),'Lazio',1900,'Roma');
INSERT INTO squadre(id, nome, anno_fondazione, citta) VALUES (nextval('squadre_seq'),'Juventus',1897,'Torino');
INSERT INTO squadre(id, nome, anno_fondazione, citta) VALUES (nextval('squadre_seq'),'Milan',1899,'Milano');
INSERT INTO squadre(id, nome, anno_fondazione, citta) VALUES (nextval('squadre_seq'),'Inter',1908,'Milano');
INSERT INTO squadre(id, nome, anno_fondazione, citta) VALUES (nextval('squadre_seq'),'Napoli',1926,'Napoli');
INSERT INTO squadre(id, nome, anno_fondazione, citta) VALUES (nextval('squadre_seq'),'Fiorentina',1926,'Firenze');
INSERT INTO squadre(id, nome, anno_fondazione, citta) VALUES (nextval('squadre_seq'),'Atalanta',1907,'Bergamo');
INSERT INTO squadre(id, nome, anno_fondazione, citta) VALUES (nextval('squadre_seq'),'Torino',1906,'Torino');
INSERT INTO squadre(id, nome, anno_fondazione, citta) VALUES (nextval('squadre_seq'),'Bologna',1909,'Bologna');
INSERT INTO squadre_tornei(squadre_id,tornei_id) VALUES (1,1);
INSERT INTO squadre_tornei(squadre_id,tornei_id) VALUES (51,1);
INSERT INTO squadre_tornei(squadre_id,tornei_id) VALUES (101,1);
INSERT INTO squadre_tornei(squadre_id,tornei_id) VALUES (151,1);
INSERT INTO squadre_tornei(squadre_id,tornei_id) VALUES (201,51);
INSERT INTO squadre_tornei(squadre_id,tornei_id) VALUES (251,51);
INSERT INTO squadre_tornei(squadre_id,tornei_id) VALUES (301,51);
INSERT INTO squadre_tornei(squadre_id,tornei_id) VALUES (351,101);
INSERT INTO squadre_tornei(squadre_id,tornei_id) VALUES (1,101);
INSERT INTO giocatori(nome,cognome,data_nascita,ruolo,codice_fiscale,altezza,squadra_id,id) VALUES('Gianluigi','Donnarumma','1999-02-25','PORTIERE','DNNG',1.96,1,nextval('giocatori_seq'));
INSERT INTO giocatori(nome,cognome,data_nascita,ruolo,codice_fiscale,altezza,squadra_id,id) VALUES('Alessandro','Bastoni','1999-04-13','DIFENSORE','BSTL',1.90,1,nextval('giocatori_seq'));
INSERT INTO giocatori(nome,cognome,data_nascita,ruolo,codice_fiscale,altezza,squadra_id,id) VALUES('Giorgio','Chiellini','1984-08-14','DIFENSORE','CHLG',1.87,1,nextval('giocatori_seq'));
INSERT INTO giocatori(nome,cognome,data_nascita,ruolo,codice_fiscale,altezza,squadra_id,id) VALUES('Leonardo','Bonucci','1987-05-01','DIFENSORE','BNCL',1.90,1,nextval('giocatori_seq'));
INSERT INTO giocatori(nome,cognome,data_nascita,ruolo,codice_fiscale,altezza,squadra_id,id) VALUES('Giovanni','Di Lorenzo','1993-08-04','DIFENSORE','DLRG',1.83,1,nextval('giocatori_seq'));
INSERT INTO giocatori(nome,cognome,data_nascita,ruolo,codice_fiscale,altezza,squadra_id,id) VALUES('Nicolo','Barella','1997-02-07','CENTROCAMPISTA','BRLN',1.72,1,nextval('giocatori_seq'));
INSERT INTO giocatori(nome,cognome,data_nascita,ruolo,codice_fiscale,altezza,squadra_id,id) VALUES('Marco','Veratti','1992-11-05','CENTROCAMPISTA','VRTM',1.65,1,nextval('giocatori_seq'));
INSERT INTO giocatori(nome,cognome,data_nascita,ruolo,codice_fiscale,altezza,squadra_id,id) VALUES('Sandro','Tonali','2000-05-08','CENTROCAMPISTA','TNLS',1.81,1,nextval('giocatori_seq'));
INSERT INTO giocatori(nome,cognome,data_nascita,ruolo,codice_fiscale,altezza,squadra_id,id) VALUES('Ciro','Immobile','1990-02-20','ATTACCANTE','MMLC',1.85,1,nextval('giocatori_seq'));
INSERT INTO giocatori(nome,cognome,data_nascita,ruolo,codice_fiscale,altezza,squadra_id,id) VALUES('Federico','Chiesa','1997-10-25','ATTACCANTE','CHSF',1.75,1,nextval('giocatori_seq'));
INSERT INTO arbitro(id, nome, cognome, codice_arbitro) VALUES (nextval('arbitro_seq'), 'Pierluigi', 'Collina', 'ARB001');
INSERT INTO arbitro(id, nome, cognome, codice_arbitro) VALUES (nextval('arbitro_seq'), 'Daniele', 'Orsato', 'ARB002');
INSERT INTO partita (id, data_ora, luogo, goals_home, goals_away, stato, arbitro_id, torneo_id, squadra_home_id, squadra_away_id) VALUES (nextval('partita_seq'), '2026-10-15 21:00:00', 'Stadio Olimpico', NULL, NULL, 'SCHEDULED', 1, 1, 1, 51);
INSERT INTO partita (id, data_ora, luogo, goals_home, goals_away, stato, arbitro_id, torneo_id, squadra_home_id, squadra_away_id) VALUES (nextval('partita_seq'), '2026-10-16 21:00:00', 'San Siro', NULL, NULL, 'SCHEDULED', 1, 1, 101, 151);
INSERT INTO partita (id, data_ora, luogo, goals_home, goals_away, stato, arbitro_id, torneo_id, squadra_home_id, squadra_away_id) VALUES (nextval('partita_seq'), '2026-10-22 18:45:00', 'Stadio Artemio Franchi', NULL, NULL, 'SCHEDULED', 1, 51, 201, 251);
INSERT INTO partita (id, data_ora, luogo, goals_home, goals_away, stato, arbitro_id, torneo_id, squadra_home_id, squadra_away_id) VALUES (nextval('partita_seq'), '2026-11-05 21:00:00', 'Gewiss Stadium', NULL, NULL, 'SCHEDULED', 1, 51, 251, 301);
INSERT INTO partita (id, data_ora, luogo, goals_home, goals_away, stato, arbitro_id, torneo_id, squadra_home_id, squadra_away_id) VALUES (nextval('partita_seq'), '2026-09-20 15:00:00', 'Stadio Renato Dall''Ara', NULL, NULL, 'SCHEDULED', 1, 101, 351, 1);
insert into credenziali (id, username, password, role) values(nextval('credenziali_seq'), 'paolo', '$2a$10$yWAIDyuEr78BBBFZ5cYh8.Nw4gUHFTRG5FwaWqNCGeOD8M4mh3.xy', 'ADMIN');